version: '3'

volumes:
  hypervisor:

services:
  libvirt:
    image: fasrc/corona-libvirt:${ONE_VERSION:-5.4}
    network_mode: host
    pid: host
    privileged: true
    restart: always
    volumes:
      - hypervisor:/var/lib/one
      - /run:/run
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /opt/corona/${ONE_VERSION:-5.4}/libvirt/libvirt.conf:/etc/libvirt/libvirt.conf:ro
      - /opt/corona/${ONE_VERSION:-5.4}/libvirt/libvirtd.conf:/etc/libvirt/libvirtd.conf:ro
      - /opt/corona/${ONE_VERSION:-5.4}/libvirt/qemu.conf:/etc/libvirt/qemu.conf:ro
    command: /root/start.sh

  hypervisor:
    image: fasrc/corona-hypervisor:${ONE_VERSION:-5.4}
    network_mode: host
    pid: host
    restart: always
    depends_on:
      - libvirt
    volumes:
      - hypervisor:/var/lib/one
      - /run:/run
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev:/dev
      - /opt/corona/${ONE_VERSION:-5.4}/one-hypervisor/sshd.conf:/etc/ssh/sshd_config:ro
      - /opt/corona/${ONE_VERSION:-5.4}/one-hypervisor/authorized_keys:/var/lib/one/.ssh/authorized_keys:ro
    command: /root/start.sh
