version: '3'

volumes:
  controller:

services:
  controller:
    image: fasrc/corona-controller:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    volumes:
      - controller:/var/lib/one
      - /opt/corona/${ONE_VERSION:-5.2}/one-controller/ssh:/var/lib/one/.ssh
    command: /root/start.sh

  libvirt:
    image: fasrc/corona-libvirt:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    privileged: true
    restart: always
    depends_on:
      - controller
    volumes:
      - controller:/var/lib/one
      - /run:/run
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /opt/corona/${ONE_VERSION:-5.2}/libvirt/libvirt.conf:/etc/libvirt/libvirt.conf:ro
      - /opt/corona/${ONE_VERSION:-5.2}/libvirt/libvirtd.conf:/etc/libvirt/libvirtd.conf:ro
      - /opt/corona/${ONE_VERSION:-5.2}/libvirt/qemu.conf:/etc/libvirt/qemu.conf:ro
    command: /root/start.sh

  hypervisor:
    image: fasrc/corona-hypervisor:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    depends_on:
      - libvirt
      - controller
    volumes:
      - controller:/var/lib/one
      - /opt/corona/${ONE_VERSION:-5.2}/one-controller/ssh:/var/lib/one/.ssh
      - /run:/run
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev:/dev
      - /opt/corona/${ONE_VERSION:-5.2}/libvirt/libvirt.conf:/etc/libvirt/libvirt.conf:ro
      - /opt/corona/${ONE_VERSION:-5.2}/libvirt/libvirtd.conf:/etc/libvirt/libvirtd.conf:ro
      - /opt/corona/${ONE_VERSION:-5.2}/one-hypervisor/sshd.conf:/etc/ssh/sshd_config:ro
    command: /root/start.sh

  novnc:
    image: fasrc/corona-novnc:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    depends_on:
      - controller
      - sunstone
    volumes:
      - controller:/var/lib/one
      - lock:/var/lock/one
      - sunstone_certs:/etc/pki/tls:ro
    environment:
      - VNC_PROXY_SUPPORT_WSS="yes"
      - VNC_PROXY_CERT="/etc/pki/tls/certs/sunstone.cer"
      - VNC_PROXY_KEY="/etc/pki/tls/private/sunstone.key"
    command: /root/start.sh

  oneflow:
    image: fasrc/corona-oneflow:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    depends_on:
      - controller
    volumes:
      - controller:/var/lib/one
    command: /root/start.sh

  onegate:
    image: fasrc/corona-onegate:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    depends_on:
      - controller
    volumes:
      - controller:/var/lib/one
    command: /root/start.sh

  memcached:
    image: memcached:latest
    network_mode: host
    pid: host
    restart: always

  sunstone:
    image: fasrc/corona-sunstone:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    privileged: true
    restart: always
    depends_on:
      - memcached
      - controller
    environment:
      - SERVER_NAME="${SERVER_NAME:-localhost}"
      - VNC_PROXY_SUPPORT_WSS="yes"
    volumes:
      - controller:/var/lib/one
      - lock:/var/lock/one
      - sunstone_certs:/etc/pki/tls

volumes:
  controller:
  lock:
  sunstone_certs:
