version: '3'

volumes:
  controller:

services:
  controller:
    image: fasrc/corona-controller:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    volumes:
      - controller:/var/lib/one
      - /opt/corona/${ONE_VERSION:-5.2}/one-controller/id_rsa:/var/lib/one/.ssh/id_rsa:ro
      - /opt/corona/${ONE_VERSION:-5.2}/one-controller/ssh_config:/var/lib/one/.ssh/config:ro
    command: /root/start.sh

  sunstone:
    image: fasrc/corona-sunstone:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    privileged: true
    restart: always
    depends_on:
      - controller
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    volumes:
      - controller:/var/lib/one

  novnc:
    image: fasrc/corona-novnc:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    volumes:
      - controller:/var/lib/one
    command: /root/start.sh

  oneflow:
    image: fasrc/corona-oneflow:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    volumes:
      - controller:/var/lib/one
    command: /root/start.sh

  onegate:
    image: fasrc/corona-onegate:${ONE_VERSION:-5.2}
    network_mode: host
    pid: host
    restart: always
    volumes:
      - controller:/var/lib/one
    command: /root/start.sh
